name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install --upgrade setuptools wheel build --system

      - name: Set package version
        run: |
          version="${{ github.event.release.tag_name }}"
          sed -i "s/^version = \".*\"/version = \"${version}\"/" pyproject.toml

      - name: Build
        run: python -m build

      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
